version: '2'
services:
  #mongo:
  #  image: mongo
  #  ports:
  #    - "27017:27017"

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.0.16 # eg: HOST_IP_ADDR=$(ipconfig getifaddr en0) docker-compose up
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "dev.betting:8:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper

  provider:
    image: sbgfeedme/provider:latest
    ports:
    - "8181:8181"
    - "8282:8282"

  feedme:
    image: feedme
    ports:
    - "8080:8080"
    environment:
      TCP_HOST: provider
      SPRING_KAFKA_BOOTSTRAPSERVERS: 192.168.0.16:9092
    depends_on:
      - kafka
